config/routes.rb
DivaQuiz::Application.routes.draw do
  resource :session, :only => [:new, :destroy, :create]
  resources :user_answers, :only => [:create]
  resources :quizzes
  resources :users
  resources :divas
  resources :questions
  resources :answers

  root :to => "sessions#new"
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :question, :quiz_id

  belongs_to :quiz

  has_many :answers, :dependent => :destroy
  has_many :user_answers, :dependent => :destroy
  has_many :participants, :through => :user_answers,
                          :source => :user

  validates :question, :uniqueness => true
  validates :quiz_id, :presence => true
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def create
    question = Question.new(params[:question])

    if question.save
      flash[:notice] = "Question successfully saved!"
    else
      flash[:notice] = question.errors.full_messages.first
    end

    redirect_to edit_quiz_path(question.quiz)
  end

  def edit
    @question = Question.find(params[:id])
  end

  def show
    @user = User.find_by_session_token(session[:session_token])

    if @user.nil?
      flas[:notice] = "Whoops! Looks like you're not logged in"
      redirect_to root_path
    end

    @question = Question.find(params[:id])
  end

  def update
    question = Question.find(params[:id])
    question.question = params[:question][:question]
    question.save!

    redirect_to edit_quiz_path(question.quiz)
  end

  def destroy
    question = Question.find(params[:id])
    flash[:notice] = "question destroyed"
    question.destroy

    redirect_to edit_quiz_path(question.quiz)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/edit.html.erb
<div class="row">

  <div class="span4">
    <h3>Question</h3>

    <%= render :partial => "shared/question_show", :locals => { :question => @question } %>

  </div>

  <div class="span4">
    <h3>Edit Question</h3>

    <%= render :partial => "shared/question_form", :locals => { :quiz => Quiz.find(@question.quiz_id), :question => @question, :class_name => "btn-success", :btn_text => "Update Question" } %>

  </div>

  <div class="span4">
    <h3>Edit Answers</h3>
    <% @question.answers.each do |a| %>
      
      <%= render :partial => "shared/answer_form", :locals => { :answer => a, :class_name => "btn-success", :btn_text => "Update Answer" } %>
      <%= button_to "Delete Answer", answer_path(a), :method => "delete", :class => "btn btn-danger" %>

    <% end %>
  </div>

</div>

app/views/questions/show.html.erb
<div class="row">
  <div class="span12">
    <h2><%= @question.question %></h2>
  </div>
</div>

<div class="row">
  <div class="span4 offset4">

    <%= simple_form_for @question, :url => user_answers_path, :method => :post do |f| %>

      <%= f.error_notification %>

      <div class="form-inputs">
        <%= f.hidden_field :question_id, :value => @question.id %>
        <%= f.hidden_field :user_id, :value => @user.id %>

        <%= f.association :answers, :collection => @question.answers, :as => :radio_buttons, :label_method => :answer, :value_method => :id %>
      </div>

      <div class="form-actions">
        <%= f.button :submit, :class => "btn btn-primary", :value => "Answer!" %>
      </div>

    <% end %>
  </div>  
</div>