config/routes.rb
DivaQuiz::Application.routes.draw do
  resource :session, :only => [:new, :destroy, :create]
  resources :user_answers, :only => [:create]
  resources :quizzes
  resources :users
  resources :divas
  resources :questions
  resources :answers

  root :to => "sessions#new"
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  def new
    @quiz = Quiz.new
  end

  def create
    quiz = Quiz.new(params[:quiz])
    quiz.save!

    redirect_to quizzes_path
  end

  def show
    @quiz = Quiz.find(params[:id])
  end

  def index
    @current_user = User.find_by_session_token(session[:session_token])
    
    @quizzes = Quiz.all
    @questions = Question.all
    @divas = Diva.all
    @users = User.all
  end

  def edit
    @quiz = Quiz.find(params[:id])
    @user = User.find_by_session_token(session[:session_token])

    if @user.nil? || @user[:session_token] != session[:session_token]
      redirect_to quizzes_path
    end
  end
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/quizzes/_form.html.erb
<%= simple_form_for quiz do |f| %>

  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">

    <% if quiz.id? %>

      <%= f.button :submit, :url => quiz_path(quiz), :class => "btn #{class_name}", :value => btn_text %>

    <% else %>

      <%= f.button :submit, :url => quizzes_path, :class => "btn #{class_name}", :value => btn_text %>

    <% end %>
  </div>

<% end %>

app/views/quizzes/edit.html.erb
<div class="row">
  <div class="span12">
    <h2><%= @quiz.name %></h2>
    <%= button_to "All Quizzes", quizzes_path, :method => :get, :class => "btn btn-inverse" %>
  </div>
</div>

<%= render :partial => "create" %>

<div class="row">
  <div class="span6">
    <h3>Current Questions</h3>

    <% if @quiz.questions.empty? %>

      <em>No Questions Yet</em>

    <% end %>

      <% @quiz.questions.each do |q| %>

      <div class="well">

        <%= render :partial => "shared/question_show", :locals => { :question => q } %>

        <%= button_to "Edit", edit_question_path(q), :method => :get, :class => "btn btn-inverse" %>
      </div>

      <% end %>
  </div>

  <div class="span6">
    <h3>Particapating Users</h3>

    <% User.all.each do |u| %>

      <% if u.started_quiz?(@quiz) || u.completed_quiz?(@quiz) %>

        <div class="well">
          
          <%= render :partial => "shared/user_show", :locals => { :user => u } %>
          <%= render :partial => "shared/user_quiz", :locals => { :quiz => @quiz, :user => u } %>

          <%= button_to "Edit", edit_user_path(u), :method => :get, :class => "btn btn-inverse" %>

          <% unless u.session_token == session[:session_token] %>
            <%= button_to "Delete", user_path(u), :method => :delete, :confirm => "Are you sure?", :class => "btn btn-danger" %>
          <% end %>

        </div>

      <% else %>

        <em>No users have participated in this quiz</em>

      <% end %>

    <% end %>
  </div>
</div>

app/views/quizzes/index.html.erb
<div class="row">
  <div clas="span4">
    <h3>Quizzes</h3>

    <% @quizzes.each do |q| %>

      <div class="well">
        <%= link_to q.name, quiz_path(q) %> <%= button_to "Take Quiz", question_path(q.questions.first), :method => :get, :class => "btn btn-success" %>
      </div>

    <% end %>
  </div>
</div>

<!-- SHOW IF USER IS ADMIN -->

<div class="row">
  <div class="span12">
    <h3>Admin Panel</h3>
    <%= button_to "New Quiz", new_quiz_path, :method => :get, :class => "btn btn-primary" %>
    <%= button_to "New Diva", new_diva_path, :method => :get, :class => "btn btn-primary" %>
  </div>
</div>

<div class="row">

  <div class="span6">
    <h3>Current Divas</h3>

    <% if @divas.empty? %>

      <em>No Divas Yet</em>

    <% else %>

      <% @divas.each do |d| %>

        <div class="well">

          <strong>Name:</strong> <%= d.name %>
          <br>
          <strong>Description:</strong>
          <p><%= d.description %></p>

          <%= button_to "Edit", edit_diva_path(d), :method => :get, :class => "btn btn-inverse" %>
          <%= button_to "Delete", diva_path(d), :method => :delete, :confirm => "Are you sure?", :class => "btn btn-danger" %>
        </div>

      <% end %>

    <% end %>
  </div>

  <div class="span6">
    <h3>Active Users</h3>

    <% if @users.empty? %>
      <em>No Questions Yet</em>
    <% end %>

    <% @users.each do |u| %>

      <div class="well">
        <%= render :partial => "shared/user_show", :locals => { :user => u } %>
        <%= button_to "Edit", edit_user_path(u), :method => :get, :class => "btn btn-inverse" %>

        <% unless @current_user.session_token == session[:session_token] %>
          <%= button_to "Delete", user_path(u), :method => :delete, :confirm => "Are you sure?", :class => "btn btn-danger" %>
        <% end %>
    </div>

    <% end %>
  </div>
</div>

app/views/quizzes/new.html.erb
<div class="row">
  <div class="span4">
    <h3>New Quiz</h3>

    <%= render :partial => "form", :locals => { :quiz => @quiz, :class_name => "btn-primary", :btn_text => "Create Quiz" } %>

  </div>
</div>

<%= render :partial => "create" %>

app/views/quizzes/show.html.erb
<div class="row">
  <div class="span4">
    <h3><%= @quiz.name %></h3>

    <% @quiz.questions.each do |q| %>

      <div class="well">
        <%= render :partial => "shared/question_show", :locals => { :question => q } %>
      </div>

    <% end %>

    <%= button_to "Edit Quiz", edit_quiz_path(@quiz), :method => :get, :class => "btn btn-inverse" %>

  </div>
</div>