config/routes.rb
DivaQuiz::Application.routes.draw do
  resource :session, :only => [:new, :destroy, :create]
  resources :user_answers, :only => [:create]
  resources :quizzes
  resources :users
  resources :divas
  resources :questions
  resources :answers

  root :to => "sessions#new"
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :answer, :question_id, :diva_id

  belongs_to :question
  belongs_to :diva
  
  has_many :user_answers, :dependent => :destroy

  validates :question_id, :presence => true
  validates :diva_id, :presence => true
end

app/models/diva.rb
class Diva < ActiveRecord::Base
  attr_accessible :name, :description

  has_many :answers
  has_many :user_answers, :through => :answers

  validates :name, :uniqueness => true

end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :question, :quiz_id

  belongs_to :quiz

  has_many :answers, :dependent => :destroy
  has_many :user_answers, :dependent => :destroy
  has_many :participants, :through => :user_answers,
                          :source => :user

  validates :question, :uniqueness => true
  validates :quiz_id, :presence => true
end

app/models/quiz.rb
class Quiz < ActiveRecord::Base
  attr_accessible :name

  has_many :questions, :dependent => :destroy
  has_many :answers, :through => :questions

  validates :name, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation

  has_secure_password

  has_many :user_answers, :dependent => :destroy
  has_many :answers, :through => :user_answers
  has_many :answered_questions, :through => :answers, :source => :question
  has_many :quizzes, :through => :answered_questions, :source => :quiz

  validates :name, :presence => true
  validates :email, :presence => true, :uniqueness => true

  def log_out
    self.session_token = nil
  end

  def my_diva(quiz)
    possible_divas = self.answers.joins(:question).where("questions.quiz_id = ?", quiz.id)
      .group(:diva_id).order("COUNT(diva_id) DESC")

    if !possible_divas.first.nil?
      possible_divas.first.diva_id
    else
      nil
    end
  end

  def started_quiz?(quiz)
    !!self.answered_questions.where(:quiz_id => quiz.id).first
  end

  def completed_quiz?(quiz)
    self.answered_questions.where(:quiz_id => quiz.id).count == quiz.questions.count
  end

  def completed_quizzes
    quizzes = []
    Quiz.all.map { |quiz| quizzes << quiz if completed_quiz?(quiz) }
    
    quizzes
  end
end

app/models/user_answer.rb
class UserAnswer < ActiveRecord::Base
  attr_accessible :user_id, :question_id, :answer_id

  belongs_to :user
  belongs_to :question
  belongs_to :answer

  validates :question_id, :uniqueness => { :scope => :user_id }
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    answer = Answer.new(params[:answer])

    if answer.save
      flash[:notice] = "Answer successfully saved!"
    else
      flash[:notice] = answer.errors.full_messages.first
    end

    quiz = answer.question.quiz
    redirect_to edit_quiz_path(quiz)
  end

  def update
    answer = Answer.find(params[:id])
    answer.answer = params[:answer][:answer]
    answer.question_id = params[:answer][:question_id]
    answer.diva_id = params[:answer][:diva_id]
    answer.save!

    redirect_to edit_question_path(answer.question)
  end

  def destroy
    answer = Answer.find(params[:id])
    flash[:notice] = "answer destroyed"
    answer.destroy

    redirect_to edit_question_path(answer.question)
  end
end

app/controllers/divas_controller.rb
class DivasController < ApplicationController
  def new
    @diva = Diva.new
  end

  def create
    @diva = Diva.new(params[:diva])

    begin
      @diva.save!
      flash[:notice] = "#{@diva.name} successfully saved!"
    rescue
      flash[:notice] = @diva.errors.full_messages.first
    end

    redirect_to quizzes_path
  end

  def edit
    @diva = Diva.find(params[:id])
  end

  def show
    @diva = Diva.find(params[:id])
    @user = User.find_by_session_token(session[:session_token])
  end

  def update
    diva = Diva.find(params[:id])
    diva.name = params[:diva][:name]
    diva.description = params[:diva][:description]
    diva.save!

    redirect_to quizzes_path
  end

  def destroy
    @diva = Diva.find(params[:id])
    flash[:notice] = "diva destroyed"
    @diva.destroy

    redirect_to quizzes_path
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def create
    question = Question.new(params[:question])

    if question.save
      flash[:notice] = "Question successfully saved!"
    else
      flash[:notice] = question.errors.full_messages.first
    end

    redirect_to edit_quiz_path(question.quiz)
  end

  def edit
    @question = Question.find(params[:id])
  end

  def show
    @user = User.find_by_session_token(session[:session_token])

    if @user.nil?
      flas[:notice] = "Whoops! Looks like you're not logged in"
      redirect_to root_path
    end

    @question = Question.find(params[:id])
  end

  def update
    question = Question.find(params[:id])
    question.question = params[:question][:question]
    question.save!

    redirect_to edit_quiz_path(question.quiz)
  end

  def destroy
    question = Question.find(params[:id])
    flash[:notice] = "question destroyed"
    question.destroy

    redirect_to edit_quiz_path(question.quiz)
  end
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  def new
    @quiz = Quiz.new
  end

  def create
    quiz = Quiz.new(params[:quiz])
    quiz.save!

    redirect_to quizzes_path
  end

  def show
    @quiz = Quiz.find(params[:id])
  end

  def index
    @current_user = User.find_by_session_token(session[:session_token])
    
    @quizzes = Quiz.all
    @questions = Question.all
    @divas = Diva.all
    @users = User.all
  end

  def edit
    @quiz = Quiz.find(params[:id])
    @user = User.find_by_session_token(session[:session_token])

    if @user.nil? || @user[:session_token] != session[:session_token]
      redirect_to quizzes_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by_email(params[:user][:email])
    session_token = SecureRandom.urlsafe_base64
    @user.session_token = session_token

    if @user.nil?
      flash[:notice] = "Looks like you don't exist yet."
    end
    
    if @user.save && @user.authenticate(params[:user][:password])
      session[:session_token] = session_token
      redirect_to quizzes_path
    else
      flash[:notice] = "Looks like you don't exist yet."
      redirect_to root_path
    end
  end

  def destroy
    user = User.find_by_session_token(session[:session_token])
    user.log_out
    session[:session_token] = nil

    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    @user.save!

    redirect_to new_session_path
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:user][:id])
    @user.name = params[:user][:name]
    @user.email = params[:user][:email]
    @user.save!

    redirect_to edit_quiz_path
  end

  def destroy
    @user = User.find(params[:id])
    flash[:notice] = "user destroyed"
    @user.destroy

    redirect_to edit_quiz_path
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/divas_helper.rb
module DivasHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_answers_helper.rb
module UserAnswersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DivaQuiz</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <container>
    <%= button_to "Log-Out", session_path, :method => :delete, :class => "btn btn-inverse" %>
    <% if flash[:notice] %>
      <div class="alert">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% end %>

    <%= yield %>
  
  </container>
</body>
</html>

app/views/shared/_answer_form.html.erb
<%= simple_form_for answer, :html => {:class => "form-inline"} do |f| %>

  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :answer %>

    <%= f.association :question, :collection => Question.all, :label_method => :question, :value_method => :id %>
    <%= f.association :diva, :collection => Diva.all, :label_method => :name, :value_method => :id %>
  </div>

  <div class="form-actions">
    <% if answer.id? %>

      <%= f.button :submit, :url => answer_path(answer), :class => "btn #{class_name}", :value => btn_text %>

    <% else %>

      <%= f.button :submit, :url => answers_path, :class => "btn #{class_name}", :value => btn_text %>

    <% end %>
  </div>

<% end %>

app/views/shared/_diva_form.html.erb
<%= simple_form_for diva, :html => { :class => "form-inline" } do |f| %>

  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description, :as => :text, :input_html => { :rows => 5 } %>
  </div>

  <div class="form-actions">

    <% if diva.id? %>

      <%= f.button :submit, :url => diva_path(diva), :class => "btn #{class_name}", :value => btn_text %>

    <% else %>

      <%= f.button :submit, :url => divas_path, :class => "btn #{class_name}", :value => btn_text %>

    <% end %>

  </div>
<% end %>

app/views/shared/_question_form.html.erb
<%= simple_form_for question, :html => {:class => "form-inline"} do |f| %>

  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.hidden_field :quiz_id, :value => quiz.id %>
    <%= f.input :question %>
  </div>

  <div class="form-actions">

    <% if question.id? %>

      <%= f.button :submit, :url => answer_path(question), :class => "btn #{class_name}", :value => btn_text %>

    <% else %>

      <%= f.button :submit, :url => questions_path, :class => "btn #{class_name}", :value => btn_text %>

    <% end %>
  </div>

<% end %>

app/views/shared/_question_show.html.erb
<strong><%= question.question %></strong>
  <ol>

    <% question.answers.each do |a| %>
      <li><%= a.answer %>, <%= a.diva.name %>
    <% end %>

  </ol>

<%= button_to "Delete Question", question_path(question), :confirm => "Are you sure?", :method => :delete, :class => "btn btn-danger" %>

app/views/shared/_user_quiz.html.erb
<br>
<strong>Diva:</strong>

<% if user.completed_quiz?(quiz) && !user.my_diva(quiz).nil? %>

  <%= Diva.find(user.my_diva(quiz)).name %>

<% else %>

  <em><%= user.name %> hasn't completed this quiz yet</em>

<% end %>

app/views/shared/_user_show.html.erb
<strong>Name:</strong> <%= user.name %>
<br>
<strong>E-Mail Address:</strong> <%= user.email %>